--------------------------------------------------------
-- Archivo creado  - jueves-febrero-06-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table W_CONSTRUCCION
--------------------------------------------------------

  CREATE TABLE "DAVID"."W_CONSTRUCCION" 
   (	"TIPOCONSTRUCCION" VARCHAR2(64 BYTE), 
	"CODTIPOCONSTRUCCION" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DAVID.W_CONSTRUCCION
SET DEFINE OFF;
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Arte rupestre','1');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Eremitorio','2');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Villa','3');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Castro','4');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Edificio Antiguo','5');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Monumento Megalítico','6');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Poblado','7');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Ermita','8');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Escultura / Estatua','9');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Restos paleontológicos','10');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Ciudad','11');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Monasterio / Convento','13');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Real Sitio;Monasterio / Convento','14');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Iglesia','15');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Castillo / Fortaleza / Atalaya','16');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Torre','17');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Catedral','18');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Ayuntamiento','19');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Plaza','20');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Colegiata','21');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Monasterio / Convento;Iglesia','22');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Palacio','23');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Real Sitio;Palacio','24');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Edificio Universitario;Palacio','25');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Palacio;Castillo / Fortaleza / Atalaya','26');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Sinagoga','27');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Casa Noble','28');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Santuario','29');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Hórreo','30');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Puerta','31');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Muralla','32');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Puente','33');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Colegio','34');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Calzada','35');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Cripta','36');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Eremitorio;Arte rupestre','37');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Puente / Calzada','38');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Necrópolis','39');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Campamento','40');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Colegiata;Iglesia','41');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Necrópolis;Santuario','42');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Minas','43');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Crucero','44');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Fuentes','45');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Despoblado','46');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Dolmen','47');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Edificio Universitario','48');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Teatro','49');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Jardín','50');
Insert into DAVID.W_CONSTRUCCION (TIPOCONSTRUCCION,CODTIPOCONSTRUCCION) values ('Sin Tipo','0');
