--------------------------------------------------------
-- Archivo creado  - jueves-febrero-06-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table W_PERIODO_HISTORICO
--------------------------------------------------------

  CREATE TABLE "DAVID"."W_PERIODO_HISTORICO" 
   (	"PERIODOHISTORICO" VARCHAR2(128 BYTE), 
	"CODPERIODOHISTORICO" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DAVID.W_PERIODO_HISTORICO
SET DEFINE OFF;
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad del Hierro;Neolítico;Edad del Bronce','1');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad del Bronce;Edad del Cobre','2');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Sin Periodo Historico','0');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad Media','4');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Romano','5');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Postpaleolítico','6');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad del Hierro','7');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad del Hierro;Edad del Bronce','8');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad del Cobre;Neolítico','9');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad Moderna;Edad Media','10');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Romano;Edad del Hierro','11');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Celta (Vetón);Edad del Hierro','12');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Visigodo;Edad del Hierro','13');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Neolítico','14');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Romano;Edad del Bronce','15');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Romano;Postpaleolítico','16');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Paleolítico','17');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad del Bronce;Paleolítico','18');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad del Cobre','19');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Romano;Celtibérico (Arévaco)','20');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Prehistoria','21');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Tardoromano','22');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad Moderna','23');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad Media;Edad del Hierro','24');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad Contemporánea','25');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Visigodo','26');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad Contemporánea;Edad Moderna','27');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Califal','28');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad Media;Romano','29');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad del Bronce;Neolítico;Edad del Cobre','30');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad del Bronce','31');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad del Bronce;Neolítico','32');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Prerromano','33');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Celta (Vetón)','34');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad Media;Visigodo','35');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad Media;Edad del Bronce;Edad del Hierro;Prerromano','36');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Paleocristiano','37');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Edad del Hierro;Neolítico','38');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Romano;Celta (Vacceo)','39');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Medieval','40');
Insert into DAVID.W_PERIODO_HISTORICO (PERIODOHISTORICO,CODPERIODOHISTORICO) values ('Celtibérico (Arévaco)','41');
