--------------------------------------------------------
-- Archivo creado  - jueves-febrero-06-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table W_TIPO_MONUMENTO
--------------------------------------------------------

  CREATE TABLE "DAVID"."W_TIPO_MONUMENTO" 
   (	"TIPOMONUMENTO" VARCHAR2(32 BYTE), 
	"CODTIPOMONUMENTO" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DAVID.W_TIPO_MONUMENTO
SET DEFINE OFF;
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Yacimientos arqueológicos','1');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Monasterios','2');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Castillos','3');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Catedrales','4');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Casas Consistoriales','5');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Plazas Mayores','6');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Iglesias y Ermitas','7');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Palacios','8');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Sinagogas','9');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Casas Nobles','10');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Santuarios','11');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Molinos','12');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Hórreos','13');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Murallas y puertas','14');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Torres','15');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Puentes','16');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Otros edificios','17');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Conjunto Etnológico','18');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Paraje pintoresco','19');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Sitio Histórico','20');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Cruceros','21');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Fuentes','22');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Esculturas','23');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Jardín Histórico','24');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Reales Sitios','25');
Insert into DAVID.W_TIPO_MONUMENTO (TIPOMONUMENTO,CODTIPOMONUMENTO) values ('Sin Tipo','0');
